-- MySQL 5.7 compatible
-- 30652: 掛機控制器，完整复制 240151（隨身商店）模板，仅替换编号与名称
-- 30653: 一鍵傳送，完整复制 240103（主城傳送）模板，仅替换编号与名称

DELETE FROM `etcitem`
WHERE `item_id` IN (30652, 30653);

INSERT INTO `etcitem` (
  `item_id`,
  `name`,
  `unidentified_name_id`,
  `identified_name_id`,
  `item_type`,
  `use_type`,
  `material`,
  `weight`,
  `invgfx`,
  `grdgfx`,
  `itemdesc_id`,
  `stackable`,
  `max_charge_count`,
  `dmg_small`,
  `dmg_large`,
  `min_lvl`,
  `max_lvl`,
  `locx`,
  `locy`,
  `mapid`,
  `bless`,
  `trade`,
  `cant_delete`,
  `can_seal`,
  `delay_id`,
  `delay_time`,
  `delay_effect`,
  `food_volume`,
  `save_at_once`,
  `classname`,
  `class`
)
SELECT
  30652,
  '掛機控制器',
  '掛機控制器',
  '掛機控制器',
  `item_type`,
  `use_type`,
  `material`,
  `weight`,
  `invgfx`,
  `grdgfx`,
  `itemdesc_id`,
  `stackable`,
  `max_charge_count`,
  `dmg_small`,
  `dmg_large`,
  `min_lvl`,
  `max_lvl`,
  `locx`,
  `locy`,
  `mapid`,
  `bless`,
  `trade`,
  `cant_delete`,
  `can_seal`,
  `delay_id`,
  `delay_time`,
  `delay_effect`,
  `food_volume`,
  `save_at_once`,
  `classname`,
  `class`
FROM `etcitem`
WHERE `item_id` = 240151;

INSERT INTO `etcitem` (
  `item_id`,
  `name`,
  `unidentified_name_id`,
  `identified_name_id`,
  `item_type`,
  `use_type`,
  `material`,
  `weight`,
  `invgfx`,
  `grdgfx`,
  `itemdesc_id`,
  `stackable`,
  `max_charge_count`,
  `dmg_small`,
  `dmg_large`,
  `min_lvl`,
  `max_lvl`,
  `locx`,
  `locy`,
  `mapid`,
  `bless`,
  `trade`,
  `cant_delete`,
  `can_seal`,
  `delay_id`,
  `delay_time`,
  `delay_effect`,
  `food_volume`,
  `save_at_once`,
  `classname`,
  `class`
)
SELECT
  30653,
  '一鍵傳送',
  '一鍵傳送',
  '一鍵傳送',
  `item_type`,
  `use_type`,
  `material`,
  `weight`,
  `invgfx`,
  `grdgfx`,
  `itemdesc_id`,
  `stackable`,
  `max_charge_count`,
  `dmg_small`,
  `dmg_large`,
  `min_lvl`,
  `max_lvl`,
  `locx`,
  `locy`,
  `mapid`,
  `bless`,
  `trade`,
  `cant_delete`,
  `can_seal`,
  `delay_id`,
  `delay_time`,
  `delay_effect`,
  `food_volume`,
  `save_at_once`,
  `classname`,
  `class`
FROM `etcitem`
WHERE `item_id` = 240103;
